ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.SecurityKt.configureSecurity
      - com.example.ExposedKt.configureExposed
      - com.example.RoutingKt.configureRouting

database:
  url: "jdbc:postgresql://localhost:5432/computer_club"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "onep!ece"
  maxPoolSize: 10